export type VFXImageOptions = keyof typeof VFXImageMap;

export const VFXImageMap = {
  fireMissile: {
    source: require("@/assets/vfx/fire/missile.png"),
    frames: 5,
    height: 33,
    width: 57,
  },
  fireSlash: {
    source: require("@/assets/vfx/fire/FireSlash.png"),
    frames: 11,
    height: 96,
    width: 95,
  },
  flameDust: {
    source: require("@/assets/vfx/fire/flame-and-dust.png"),
    frames: 31,
    height: 75,
    width: 47,
  },
  flameWall: {
    source: require("@/assets/vfx/fire/wall-burst.png"),
    frames: 7,
    height: 64,
    width: 48,
  },
  fireRain: {
    source: require("@/assets/vfx/fire/fire-rain.png"),
    frames: 29,
    height: 64,
    width: 48,
  },
  dragonBreath: {
    source: require("@/assets/vfx/fire/Dragon-Breath.png"),
    frames: 8,
    height: 176,
    width: 256,
  },
  fireBeam: {
    source: require("@/assets/vfx/fire/beam.png"),
    frames: 8,
    height: 192,
    width: 64,
    rotate: -90,
  },
  iceBlock: {
    source: require("@/assets/vfx/ice/floating-block.png"),
    frames: 21,
    height: 192,
    width: 80,
  },
  ambiguousSparks: {
    source: require("@/assets/vfx/misc/ambiguous-sparks.png"),
    frames: 14,
    height: 48,
    width: 48,
  },
  splash: {
    source: require("@/assets/vfx/water/splash.png"),
    frames: 17,
    height: 64,
    width: 64,
  },
  coldSmoke: {
    source: require("@/assets/vfx/ice/cold-smoke.png"),
    frames: 17,
    height: 64,
    width: 70,
    rotate: 45,
  },
  steam: {
    source: require("@/assets/vfx/water/steam.png"),
    frames: 17,
    height: 64,
    width: 70,
    rotate: 45,
  },
  rainCall: {
    source: require("@/assets/vfx/water/rain-call.png"),
    frames: 14,
    height: 48,
    width: 48,
  },
  spike: {
    source: require("@/assets/vfx/ice/spike.png"),
    frames: 17,
    height: 111,
    width: 111,
  },
  iceOrb: {
    source: require("@/assets/vfx/ice/orb.png"),
    frames: 6,
    height: 48,
    width: 48,
  },
  torrent: {
    source: require("@/assets/vfx/water/torrent.png"),
    frames: 18,
    height: 192,
    width: 64,
  },
  massSpikes: {
    source: require("@/assets/vfx/ice/massive-spikes.png"),
    frames: 16,
    height: 64,
    width: 48,
  },
  puft: {
    source: require("@/assets/vfx/air/puft.png"),
    frames: 6,
    height: 32,
    width: 32,
  },
  sparks: {
    source: require("@/assets/vfx/lightning/spark.png"),
    frames: 11,
    height: 64,
    width: 64,
  },
  lightning: {
    source: require("@/assets/vfx/lightning/lightning-bolt.png"),
    frames: 15,
    height: 159,
    width: 111,
  },
  thunderClap: {
    source: require("@/assets/vfx/lightning/clap.png"),
    frames: 16,
    height: 48,
    width: 48,
  },
  lightningRay: {
    source: require("@/assets/vfx/lightning/long-bolt.png"),
    frames: 5,
    height: 48,
    width: 144,
  },
  windBlades: {
    source: require("@/assets/vfx/air/blades.png"),
    frames: 6,
    height: 64,
    width: 64,
  },
  groundSlash: {
    source: require("@/assets/vfx/air/ground-slash.png"),
    frames: 6,
    height: 64,
    width: 80,
  },
  tornado: {
    source: require("@/assets/vfx/air/tornado.png"),
    frames: 17,
    height: 143,
    width: 128,
  },
  rockDrop: {
    source: require("@/assets/vfx/earth/rock-drop.png"),
    frames: 13,
    height: 160,
    width: 96,
  },
  rockBullet: {
    source: require("@/assets/vfx/earth/rock-bullet.png"),
    frames: 14,
    height: 160,
    width: 192,
  },
  bloodCone: {
    source: require("@/assets/vfx/blood/blood-cone.png"),
    frames: 8,
    height: 48,
    width: 48,
    mirror: true,
  },
  bloodBurst: {
    source: require("@/assets/vfx/blood/blood-cone.png"),
    frames: 6,
    height: 60,
    width: 60,
  },
  bloodLongBolts: {
    source: require("@/assets/vfx/blood/long-bolt.png"),
    frames: 6,
    height: 111,
    width: 144,
  },
  bloodSimpleBolts: {
    source: require("@/assets/vfx/blood/simple-bolts.png"),
    frames: 6,
    height: 60,
    width: 60,
    rotate: -90,
  },
};
