export type VFXImageOptions = keyof typeof VFXImageMap;

export const VFXImageMap = {
  fireMissile: {
    source: require("@/assets/vfx/fire/missile.webp"),
    frames: 5,
    height: 33,
    width: 57,
  },
  fireSlash: {
    source: require("@/assets/vfx/fire/FireSlash.webp"),
    frames: 11,
    height: 96,
    width: 95,
  },
  flameDust: {
    source: require("@/assets/vfx/fire/flame-and-dust.webp"),
    frames: 31,
    height: 75,
    width: 47,
  },
  flameWall: {
    source: require("@/assets/vfx/fire/wall-burst.webp"),
    frames: 7,
    height: 64,
    width: 48,
  },
  fireRain: {
    source: require("@/assets/vfx/fire/fire-rain.webp"),
    frames: 29,
    height: 64,
    width: 48,
  },
  dragonBreath: {
    source: require("@/assets/vfx/fire/Dragon-Breath.webp"),
    frames: 8,
    height: 176,
    width: 256,
  },
  fireBeam: {
    source: require("@/assets/vfx/fire/beam.webp"),
    frames: 8,
    height: 192,
    width: 64,
    rotate: -90,
  },
  iceBlock: {
    source: require("@/assets/vfx/ice/floating-block.webp"),
    frames: 21,
    height: 96,
    width: 80,
  },
  ambiguousSparks: {
    source: require("@/assets/vfx/lightning/ambiguous-sparks.webp"),
    frames: 14,
    height: 48,
    width: 48,
  },
  splash: {
    source: require("@/assets/vfx/water/splash.webp"),
    frames: 17,
    height: 64,
    width: 64,
  },
  coldSmoke: {
    source: require("@/assets/vfx/ice/cold-smoke.webp"),
    frames: 17,
    height: 64,
    width: 70,
    rotate: 45,
  },
  steam: {
    source: require("@/assets/vfx/water/steam.webp"),
    frames: 17,
    height: 64,
    width: 70,
    rotate: 45,
  },
  rainCall: {
    source: require("@/assets/vfx/water/rain-call.webp"),
    frames: 14,
    height: 48,
    width: 48,
  },
  spike: {
    source: require("@/assets/vfx/ice/spike.webp"),
    frames: 17,
    height: 111,
    width: 111,
  },
  iceOrb: {
    source: require("@/assets/vfx/ice/orb.webp"),
    frames: 6,
    height: 48,
    width: 48,
  },
  torrent: {
    source: require("@/assets/vfx/water/torrent.webp"),
    frames: 18,
    height: 192,
    width: 64,
  },
  massSpikes: {
    source: require("@/assets/vfx/ice/massive-spikes.webp"),
    frames: 16,
    height: 64,
    width: 48,
  },
  puft: {
    source: require("@/assets/vfx/air/puft.webp"),
    frames: 6,
    height: 32,
    width: 32,
  },
  sparks: {
    source: require("@/assets/vfx/lightning/spark.webp"),
    frames: 11,
    height: 64,
    width: 64,
  },
  lightning: {
    source: require("@/assets/vfx/lightning/lightning-bolt.webp"),
    frames: 15,
    height: 159,
    width: 111,
  },
  thunderClap: {
    source: require("@/assets/vfx/lightning/clap.webp"),
    frames: 16,
    height: 48,
    width: 48,
  },
  lightningRay: {
    source: require("@/assets/vfx/lightning/long-bolt.webp"),
    frames: 5,
    height: 48,
    width: 144,
  },
  windBlades: {
    source: require("@/assets/vfx/air/blades.webp"),
    frames: 6,
    height: 64,
    width: 64,
  },
  groundSlash: {
    source: require("@/assets/vfx/air/ground-slash.webp"),
    frames: 6,
    height: 64,
    width: 80,
  },
  tornado: {
    source: require("@/assets/vfx/air/tornado.webp"),
    frames: 17,
    height: 143,
    width: 128,
  },
  rockDrop: {
    source: require("@/assets/vfx/earth/rock-drop.webp"),
    frames: 13,
    height: 160,
    width: 96,
  },
  rockCollider: {
    source: require("@/assets/vfx/earth/rock-collider.webp"),
    frames: 14,
    height: 80,
    width: 192,
  },
  bloodCone: {
    source: require("@/assets/vfx/blood/blood-cone.webp"),
    frames: 8,
    height: 48,
    width: 48,
    mirror: true,
  },
  bloodBurst: {
    source: require("@/assets/vfx/blood/blood-burst.webp"),
    frames: 6,
    height: 60,
    width: 60,
  },
  bloodLongBolts: {
    source: require("@/assets/vfx/blood/long-bolt.webp"),
    frames: 6,
    height: 111,
    width: 144,
  },
  bloodSimpleBolts: {
    source: require("@/assets/vfx/blood/simple-bolts.webp"),
    frames: 6,
    height: 60,
    width: 60,
    rotate: -90,
  },
  arrow: {
    source: require("@/assets/vfx/physical/arrow.webp"),
    frames: 4,
    height: 30,
    width: 30,
  },
  projectileHit: {
    source: require("@/assets/vfx/physical/projectile-hit.webp"),
    frames: 4,
    height: 48,
    width: 48,
  },
  bloodSplash: {
    source: require("@/assets/vfx/blood/blood-small.webp"),
    frames: 5,
    height: 20,
    width: 20,
  },
};
